# Generated by Django 3.0.5 on 2020-04-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ups_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.CharField(choices=[('VERY_SATISFIED', 'Very Satisfied'), ('SATISFIED', 'Satisfied'), ('OK', 'OK'), ('DISATISFIED', 'Disatisfied'), ('VERY_DISATISFIED', 'Very Disatisfied')], default='SATISFIED', max_length=50)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
